CREATE TABLE IF NOT EXISTS StudentFaceData (
    FaceDataID    INT PRIMARY KEY AUTO_INCREMENT,
    StudentID     INT NOT NULL UNIQUE,
    FaceEncoding  LONGBLOB,
    EncodingType  VARCHAR(32) DEFAULT 'ml_encoding',
    RegisteredAt  DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt     DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);